"""Generate structured PR briefings using LLM with senior-voice prompting."""
import logging
from dataclasses import dataclass

from src.analyzers.diff_parser import FileChange
from src.analyzers.risk_scorer import RiskFlag
from src.briefing.prompt_templates import SYSTEM_PROMPT
from src.llm.base import LLMProvider

logger = logging.getLogger(__name__)


@dataclass
class Briefing:
    """A structured PR briefing generated by the LLM."""

    what_changed: str
    blast_radius: str
    risk_flags: str
    questions: str
    raw_response: str


def generate_briefing(
    provider: LLMProvider,
    changes: list[FileChange],
    changed_symbols: dict[str, list[str]],
    flags: list[RiskFlag],
) -> Briefing:
    """Generate a structured briefing from diff analysis.

    Args:
        provider: LLM provider instance to call for generation.
        changes: List of parsed file changes from the diff.
        changed_symbols: Mapping of file paths to changed function/class names.
        flags: Risk flags detected by heuristic analysis.

    Returns:
        A Briefing object with structured sections.

    Raises:
        RuntimeError: If the LLM provider fails to generate a response.
    """
    prompt = _assemble_prompt(changes, changed_symbols, flags)
    logger.info("Assembled prompt (%d chars)", len(prompt))

    try:
        raw_response = provider.generate(prompt)
    except Exception as exc:
        raise RuntimeError(f"LLM provider failed to generate briefing: {exc}") from exc

    logger.info("Generated briefing (%d chars)", len(raw_response))

    # Parse the LLM response into structured sections.
    # The LLM is prompted to follow a specific format, so we parse by section headers.
    sections = _parse_sections(raw_response)

    briefing = Briefing(
        what_changed=sections.get("what_changed", ""),
        blast_radius=sections.get("blast_radius", ""),
        risk_flags=sections.get("risk_flags", ""),
        questions=sections.get("questions", ""),
        raw_response=raw_response,
    )

    _validate_briefing(briefing)
    return briefing


def _assemble_prompt(
    changes: list[FileChange],
    changed_symbols: dict[str, list[str]],
    flags: list[RiskFlag],
) -> str:
    """Assemble the full prompt: system prompt + structured context."""
    parts: list[str] = [SYSTEM_PROMPT]

    parts.append("\n---\n## CONTEXT\n")

    parts.append("### Changed files\n")
    for change in changes:
        if change.is_new_file:
            action = "new file"
        elif change.is_deleted_file:
            action = "deleted"
        else:
            action = "modified"

        symbols = changed_symbols.get(change.path, [])
        symbol_str = f" — symbols: {', '.join(symbols)}" if symbols else ""
        parts.append(
            f"- `{change.path}` ({change.language}, {action})"
            f" +{len(change.added_lines)}/-{len(change.removed_lines)} lines{symbol_str}\n"
        )

    parts.append("\n### Risk flags\n")
    if flags:
        for flag in flags:
            loc = f":{flag.line}" if flag.line is not None else ""
            parts.append(f"- [{flag.flag}] `{flag.file}{loc}` — {flag.snippet}\n")
    else:
        parts.append("None detected.\n")

    return "".join(parts)


def _parse_sections(response: str) -> dict[str, str]:
    """Parse LLM response into section keys.

    The LLM is prompted to structure output as:
    1. WHAT CHANGED
    2. BLAST RADIUS
    3. RISK FLAGS
    4. QUESTIONS

    This parser extracts content for each numbered section. If a section is not
    found, it returns an empty string for that section.
    """
    sections: dict[str, str] = {
        "what_changed": "",
        "blast_radius": "",
        "risk_flags": "",
        "questions": "",
    }

    # Check for section headers in order of specificity (longest first)
    # Only use full section names to avoid matching content lines like "1. Why?"
    section_headers = [
        ("1. WHAT CHANGED", "what_changed"),
        ("2. BLAST RADIUS", "blast_radius"),
        ("3. RISK FLAGS", "risk_flags"),
        ("4. QUESTIONS", "questions"),
    ]

    lines = response.split("\n")
    current_section = None
    current_content: list[str] = []
    found_sections = set()

    for line in lines:
        # Check if this line starts a new section (full header match only)
        section_found = False
        stripped = line.strip()
        for section_header, section_key in section_headers:
            if stripped.startswith(section_header):
                # Save the previous section content
                if current_section:
                    sections[current_section] = "\n".join(current_content).strip()
                current_section = section_key
                found_sections.add(section_key)
                current_content = []
                section_found = True
                break

        # If this line doesn't start a new section and we're in a section, collect the content
        if not section_found and current_section is not None:
            current_content.append(line)

    # Save the last section
    if current_section:
        sections[current_section] = "\n".join(current_content).strip()

    # Log which sections were found for debugging
    missing = set(sections.keys()) - found_sections
    if missing:
        logger.warning("Missing expected sections in LLM response: %s", ", ".join(sorted(missing)))

    return sections


def _validate_briefing(briefing: Briefing) -> None:
    """Validate that briefing sections have meaningful content.

    Logs warnings if any section is unexpectedly empty, which indicates the LLM
    may not have followed the expected format or the parsing failed.
    """
    if not briefing.what_changed.strip():
        logger.warning("Briefing section 'what_changed' is empty")
    if not briefing.blast_radius.strip():
        logger.warning("Briefing section 'blast_radius' is empty")
    if not briefing.risk_flags.strip():
        logger.warning("Briefing section 'risk_flags' is empty")
    if not briefing.questions.strip():
        logger.warning("Briefing section 'questions' is empty")
