"""Generate structured PR briefings using LLM with senior-voice prompting."""
import logging
from dataclasses import dataclass

from src.analyzers.diff_parser import FileChange
from src.analyzers.risk_scorer import RiskFlag
from src.briefing.prompt_templates import SYSTEM_PROMPT
from src.context.codebase_index import RelatedChunk
from src.context.git_history import FileHistory, RecentPR
from src.llm.base import LLMProvider

logger = logging.getLogger(__name__)

_MAX_PROMPT_CHARS = 24_000  # ~6k tokens; safely under Groq free-tier 12k TPM limit
_MAX_CHANGED_FILES_IN_PROMPT = 20  # cap file list for large PRs; show most-changed first
_MAX_HISTORY_FILES = 10
_MAX_RAG_CHUNKS = 3
_MAX_CHUNK_CHARS = 400


@dataclass
class Briefing:
    """A structured PR briefing generated by the LLM."""

    what_changed: str
    blast_radius: str
    risk_flags: str
    questions: str
    raw_response: str


def generate_briefing(
    provider: LLMProvider,
    changes: list[FileChange],
    changed_symbols: dict[str, list[str]],
    flags: list[RiskFlag],
    related_code: dict[str, list[RelatedChunk]] | None = None,
    git_history: dict[str, FileHistory] | None = None,
    recent_prs: list[RecentPR] | None = None,
) -> Briefing:
    """Generate a structured briefing from diff analysis.

    Args:
        provider: LLM provider instance to call for generation.
        changes: List of parsed file changes from the diff.
        changed_symbols: Mapping of file paths to changed function/class names.
        flags: Risk flags detected by heuristic analysis.
        related_code: Optional mapping of file paths to semantically similar chunks from the repo.
        git_history: Optional mapping of file paths to their recent commit history.
        recent_prs: Optional list of recently merged PRs touching the same files.

    Returns:
        A Briefing object with structured sections.

    Raises:
        RuntimeError: If the LLM provider fails to generate a response.
    """
    prompt = _assemble_prompt(changes, changed_symbols, flags, related_code, git_history, recent_prs)
    logger.info("Assembled prompt (%d chars)", len(prompt))

    try:
        raw_response = provider.generate(prompt)
    except Exception as exc:
        raise RuntimeError(f"LLM provider failed to generate briefing: {exc}") from exc

    logger.info("Generated briefing (%d chars)", len(raw_response))

    # Parse the LLM response into structured sections.
    # The LLM is prompted to follow a specific format, so we parse by section headers.
    sections = _parse_sections(raw_response)

    briefing = Briefing(
        what_changed=sections.get("what_changed", ""),
        blast_radius=sections.get("blast_radius", ""),
        risk_flags=sections.get("risk_flags", ""),
        questions=sections.get("questions", ""),
        raw_response=raw_response,
    )

    _validate_briefing(briefing)
    return briefing


def _assemble_prompt(
    changes: list[FileChange],
    changed_symbols: dict[str, list[str]],
    flags: list[RiskFlag],
    related_code: dict[str, list[RelatedChunk]] | None = None,
    git_history: dict[str, FileHistory] | None = None,
    recent_prs: list[RecentPR] | None = None,
) -> str:
    """Assemble the full prompt: system prompt + structured context."""
    parts: list[str] = [SYSTEM_PROMPT]

    parts.append("\n---\n## CONTEXT\n")

    parts.append("### Changed files\n")
    sorted_changes = sorted(changes, key=lambda c: len(c.added_lines) + len(c.removed_lines), reverse=True)
    shown = sorted_changes[:_MAX_CHANGED_FILES_IN_PROMPT]
    for change in shown:
        if change.is_new_file:
            action = "new file"
        elif change.is_deleted_file:
            action = "deleted"
        else:
            action = "modified"

        symbols = changed_symbols.get(change.path, [])
        symbol_str = f" — symbols: {', '.join(symbols)}" if symbols else ""
        parts.append(
            f"- `{change.path}` ({change.language}, {action})"
            f" +{len(change.added_lines)}/-{len(change.removed_lines)} lines{symbol_str}\n"
        )
    if len(changes) > _MAX_CHANGED_FILES_IN_PROMPT:
        parts.append(f"- ... and {len(changes) - _MAX_CHANGED_FILES_IN_PROMPT} more file(s) omitted\n")

    parts.append("\n### Risk flags\n")
    if flags:
        for flag in flags:
            loc = f":{flag.line}" if flag.line is not None else ""
            parts.append(f"- [{flag.flag}] `{flag.file}{loc}` — {flag.snippet}\n")
    else:
        parts.append("None detected.\n")

    if git_history:
        parts.append("\n### Recent activity on touched files\n")
        for file_path, history in list(git_history.items())[:_MAX_HISTORY_FILES]:
            if not history.recent_commits and not history.limited_history:
                continue
            parts.append(f"\n**`{file_path}`**")
            if history.limited_history and not history.recent_commits:
                parts.append(" — limited history (shallow clone)\n")
            else:
                if history.limited_history:
                    parts.append(" (history may be truncated — shallow clone)")
                parts.append("\n")
                for commit in history.recent_commits:
                    parts.append(f"- `{commit.sha}` {commit.message}\n")

    if recent_prs:
        parts.append("\n### Recent merged PRs touching these files\n")
        for pr in recent_prs:
            desc = f" — {pr.body_first_line}" if pr.body_first_line else ""
            parts.append(f"- PR #{pr.number}: \"{pr.title}\"{desc}\n")

    if related_code:
        parts.append("\n### Related code (semantically similar, from elsewhere in repo)\n")
        for file_path, chunks in related_code.items():
            if not chunks:
                continue
            parts.append(f"\n**Related to `{file_path}`:**\n")
            for chunk in chunks[:_MAX_RAG_CHUNKS]:
                snippet = chunk.chunk_text[:_MAX_CHUNK_CHARS]
                if len(chunk.chunk_text) > _MAX_CHUNK_CHARS:
                    snippet += "\n..."
                parts.append(f"- `{chunk.file_path}` ({chunk.label}):\n```\n{snippet}\n```\n")

    prompt = "".join(parts)
    if len(prompt) > _MAX_PROMPT_CHARS:
        logger.warning("Prompt exceeded %d chars (%d) — truncating", _MAX_PROMPT_CHARS, len(prompt))
        prompt = prompt[:_MAX_PROMPT_CHARS] + "\n\n[Context truncated to fit model token budget]\n"
    return prompt


def _parse_sections(response: str) -> dict[str, str]:
    """Parse LLM response into section keys.

    The LLM is prompted to structure output as:
    1. WHAT CHANGED
    2. BLAST RADIUS
    3. RISK FLAGS
    4. QUESTIONS

    This parser extracts content for each numbered section. If a section is not
    found, it returns an empty string for that section.
    """
    sections: dict[str, str] = {
        "what_changed": "",
        "blast_radius": "",
        "risk_flags": "",
        "questions": "",
    }

    # Check for section headers in order of specificity (longest first)
    # Only use full section names to avoid matching content lines like "1. Why?"
    section_headers = [
        ("1. WHAT CHANGED", "what_changed"),
        ("2. BLAST RADIUS", "blast_radius"),
        ("3. RISK FLAGS", "risk_flags"),
        ("4. QUESTIONS", "questions"),
    ]

    lines = response.split("\n")
    current_section = None
    current_content: list[str] = []
    found_sections = set()

    for line in lines:
        # Check if this line starts a new section (full header match only)
        section_found = False
        stripped = line.strip()
        for section_header, section_key in section_headers:
            if stripped.startswith(section_header):
                # Save the previous section content
                if current_section:
                    sections[current_section] = "\n".join(current_content).strip()
                current_section = section_key
                found_sections.add(section_key)
                current_content = []
                section_found = True
                break

        # If this line doesn't start a new section and we're in a section, collect the content
        if not section_found and current_section is not None:
            current_content.append(line)

    # Save the last section
    if current_section:
        sections[current_section] = "\n".join(current_content).strip()

    # Log which sections were found for debugging
    missing = set(sections.keys()) - found_sections
    if missing:
        logger.warning("Missing expected sections in LLM response: %s", ", ".join(sorted(missing)))

    return sections


def _validate_briefing(briefing: Briefing) -> None:
    """Validate that briefing sections have meaningful content.

    Logs warnings if any section is unexpectedly empty, which indicates the LLM
    may not have followed the expected format or the parsing failed.
    """
    if not briefing.what_changed.strip():
        logger.warning("Briefing section 'what_changed' is empty")
    if not briefing.blast_radius.strip():
        logger.warning("Briefing section 'blast_radius' is empty")
    if not briefing.risk_flags.strip():
        logger.warning("Briefing section 'risk_flags' is empty")
    if not briefing.questions.strip():
        logger.warning("Briefing section 'questions' is empty")
